import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { FC } from 'react';

const Home: FC = () => {
  return (
    <div>
      <Head>
        <title>Citalo blog</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <h1>Welcome to Citalobooks</h1>
      <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora,
        veniam.
      </p>
      <br />
      <br />
      <Link href={'/recenzije'}>All posts</Link>
    </div>
  );
};

export default Home;

// export { getStaticProps };
